title: Introduction
theme : minima
author: RyzeOng
email: someone_0209@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Introduction for my blog.
# social links
twitter_username: ryze_0209 # DO NOT include the @ character, or else the build will fail!
github_username:  RyzeOng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
